POST /sign/in HTTP/1.1
Content-Type: application/json
Content-Length: 76
Host: localhost:8080

{
  "username" : "tester",
  "password" : "password123"
}

###
# 쿠키정보를 기억하지 않도록 설정에서 해제하기 cokie로 검색 
POST /sign/refresh HTTP/1.1
Content-Type: application/json
Content-Length: 76
Host: localhost:8080
Cookie: refresh-token=EyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIwMTllZmJlYi01NGYyLWQ0N2YtNmZhZi03NWQwNzBjN2MzZDgiLCJleHAiOjE3ODIzNDgzNjYsImlhdCI6MTc4MjM0NDc2Nn0.V7YGXP6l41nGya00Cb2j8qPG8-r-A07Md636K2RpYBualQSj7SG8gK5YTZv1enf-q70NvBmU3PY0MAY4cMRIUA

###

GET /posts?q= HTTP/1.1
Content-Type: application/json
Content-Length: 76
Host: localhost:8080
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIwMTllZmJlYi01NGYyLWQ0N2YtNmZhZi03NWQwNzBjN2MzZDgiLCJleHAiOjE3ODIzNDgzNjYsImlhdCI6MTc4MjM0NDc2Nn0.V7YGXP6l41nGya00Cb2j8qPG8-r-A07Md636K2RpYBualQSj7SG8gK5YTZv1enf-q70NvBmU3PY0MAY4cMRIUA

{
  "pageNo": 1,
  "pageSize": 10
}