spring.application.name=demo-functional-endpoints
# docker for local dev
spring.docker.compose.lifecycle-management=start-only
spring.sql.init.mode=always
# datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver
# modulith
spring.modulith.detection-strategy=explicitly-annotated
spring.modulith.moments.enable-time-machine=true 
spring.modulith.moments.granularity=hours
spring.modulith.moments.locale=ko_KR
spring.modulith.moments.zone-id=Asia/Seoul
spring.modulith.moments.quarter-start-month=APRIL
spring.modulith.events.jdbc.schema-initialization.enabled=true
spring.modulith.events.completion-mode=archive
# logging
logging.level.org.springframework.security.web.FilterChainProxy=TRACE
# jwt
jwt.key=ehdgoanfrhkqorentksdlakfmrhekfgehfhrgksmsladlqhdngktkdnflskfkakstp

# secutiry 
logging.level.org.springframework.security=trace

# audielog
audit.security.integrity-key=asimovwiao
app.security.encryption-key=sdjklavaksldjklda

# HTTPS / Cookie Security
app.cookie.secure=false